// Stable protocol barrel: preserve the pre-split public surface while focused
// modules own schemas, types, command mapping, and wire helpers.

export {
	JSON_RPC_VERSION,
	RpcIdSchema,
	UnknownMethodParamsSchema,
	MessageSendParamsSchema,
	SubscribeParamsSchema,
	EmptyParamsSchema,
	MAX_PRESENCE_HINT_FIELD_BYTES,
	PresenceHintParamsSchema,
	MessageSendRequestSchema,
	InterruptPayloadSchema,
	InterruptParamsSchema,
	InterruptResultSchema,
	InterruptRequestSchema,
	SubscribeRequestSchema,
	StatusRequestSchema,
	GetMessageRequestSchema,
	ClearRequestSchema,
	AbortRequestSchema,
	PresenceHintResultSchema,
	MAX_MEMBER_STATUS_TARGET_BYTES,
	MemberStatusParamsSchema,
	MemberStatusResultSchema,
	PresenceHintRequestSchema,
	MemberStatusRequestSchema,
	MemberStatusCommandSchema,
	MemberStatusTargetParamsSchema,
	MemberStatusTargetRequestSchema,
	MemberStatusTargetCommandSchema,
} from "./protocol/wire-base.ts";

export {
	MemberMessageParamsSchema,
	MemberFollowUpParamsSchema,
	MemberRedirectParamsSchema,
	MemberFollowUpRequestSchema,
	MemberRedirectRequestSchema,
	MemberFollowUpCommandSchema,
	MemberRedirectCommandSchema,
	MemberRequestParamsSchema,
	MemberRequestRequestSchema,
	MemberRequestCommandSchema,
	MemberRequestResultSchema,
	MemberRequestStartParamsSchema,
	MemberRequestStartRequestSchema,
	MemberRequestStartCommandSchema,
	MemberRequestListParamsSchema,
	MemberRequestListRequestSchema,
	MemberRequestListCommandSchema,
	MemberRequestWaitParamsSchema,
	MemberRequestWaitRequestSchema,
	MemberRequestWaitCommandSchema,
	MemberResponseParamsSchema,
	MemberResponseRequestSchema,
	MemberResponseCommandSchema,
	MemberUpdateNotificationSchema,
	MemberUpdateResultSchema,
	MemberUpdateIdleSchemaExport,
	MemberInterruptParamsSchema,
	MemberInterruptRequestSchema,
	MemberInterruptCommandSchema,
	MemberInterruptResultSchema,
} from "./protocol/wire-members.ts";

export {
	MemberInboxSendParamsSchema,
	CrewBroadcastParamsSchema,
	MemberInboxSendRequestSchema,
	CrewBroadcastRequestSchema,
	MemberInboxSendCommandSchema,
	CrewBroadcastCommandSchema,
	GuestJoinParamsSchema,
	GuestJoinRpcRequestSchema,
	GuestJoinCommandSchema,
	GuestJoinResultSchema,
	GuestLeaveParamsSchema,
	GuestSendParamsSchema,
	GuestSendResultSchema,
	GuestSendCommandSchema,
	GuestLeaveRequestSchema,
	GuestLeaveCommandSchema,
	MemberMessageResultSchema,
	MemberInboxSendResultSchema,
	CrewBroadcastResultSchema,
	MAX_MEMBER_IDLE_WAIT_TIMEOUT,
	MIN_MEMBER_IDLE_WAIT_TIMEOUT,
} from "./protocol/wire-guests.ts";

export {
	MemberIdleWaitParamsSchema,
	MemberIdleWaitSubscribeResultSchema,
	MemberIdleWaitRequestSchema,
	MemberIdleWaitCommandSchema,
	MemberIdleWaitNotificationSchema,
	KnownRequestSchema,
	GenericRequestSchema,
	RpcRequestSchema,
	RpcErrorSchema,
	ResponseIdSchema,
	StatusResultSchema,
	SendResultSchema,
	GetMessageResultSchema,
	ClearResultSchema,
	SubscribeResultSchema,
	EmptyResultSchema,
	MemberRequestListResultSchema,
	MemberRequestWaitResultSchema,
	RpcMethodResultSchema,
	RpcResponseSchema,
	TurnEndNotificationSchema,
} from "./protocol/wire-rpc.ts";

export {
	MessageSendCommandSchema,
	InterruptCommandSchema,
	SubscribeCommandSchema,
	StatusCommandSchema,
	GetMessageCommandSchema,
	ClearCommandSchema,
	AbortCommandSchema,
	PresenceHintCommandSchema,
	RPC_ERROR,
	RpcCommandResponseSchema,
	RpcTurnEndNotificationSchema,
} from "./protocol/command-schemas.ts";

export type { RpcCommandResponse, RpcTurnEndNotification } from "./protocol/command-schemas.ts";

export {
	isMemberInterruptResult,
	isMemberMessageResult,
	isMemberInboxSendResult,
	isCrewBroadcastResult,
} from "./protocol/protocol-types.ts";

export type {
	RpcId,
	RpcRequest,
	MessageSendRequest,
	InterruptParams,
	InterruptResult,
	InterruptRequest,
	SubscribeRequest,
	StatusRequest,
	GetMessageRequest,
	ClearRequest,
	AbortRequest,
	PresenceHintParams,
	MemberStatusParams,
	MemberIdleWaitParams,
	MemberStatusCommand,
	MemberStatusResult,
	MemberStatusTargetParams,
	MemberStatusTargetCommand,
	MemberRequestParams,
	MemberRequestCommand,
	MemberRequestStartParams,
	MemberRequestStartCommand,
	MemberRequestListCommand,
	MemberRequestWaitCommand,
	MemberRequestResult,
	MemberResponseParams,
	MemberUpdateResult,
	MemberUpdateIdle,
	MemberChannelUpdate,
	MemberResponseCommand,
	MemberInterruptParams,
	MemberInterruptCommand,
	MemberInterruptResult,
	MemberMessageParams,
	MemberFollowUpParams,
	MemberRedirectParams,
	MemberInboxSendParams,
	CrewBroadcastParams,
	GuestJoinParams,
	GuestJoinResult,
	GuestJoinCommand,
	GuestSendCommand,
	GuestSendParams,
	GuestSendResult,
	GuestLeaveParams,
	GuestLeaveCommand,
	MemberFollowUpCommand,
	MemberRedirectCommand,
	MemberMessageResult,
	PresenceHintRequest,
	PresenceHintResult,
	MessageSendParams,
	MessageSendPayload,
	SubscribeParams,
	StatusParams,
	GetMessageParams,
	ClearParams,
	AbortParams,
	StatusResult,
	SendResult,
	DeliveryIntent,
	DeliveryDisposition,
	GetMessageResult,
	ClearResult,
	SubscribeResult,
	AbortResult,
	RpcError,
	RpcWireResponse,
	RpcMethodResult,
	RpcNotification,
	RpcCommand,
	RpcInboundCommand,
	MessageSendCommand,
	InterruptCommand,
	SubscribeCommand,
	StatusCommand,
	GetMessageCommand,
	ClearCommand,
	AbortCommand,
	PresenceHintCommand,
	MemberInboxSendCommand,
	CrewBroadcastCommand,
	MemberInboxSendResult,
	CrewBroadcastRpcResult,
	MemberIdleWaitCommand,
	MemberIdleWaitSubscribeResult,
	RpcSendCommand,
	RpcSubscribeCommand,
} from "./protocol/protocol-types.ts";

export {
	isPresenceHintParams,
	isRpcRequest,
	isRpcResponse,
	isTurnEndNotification,
	isMemberUpdateNotification,
} from "./protocol/protocol-guards.ts";

export type { ProtocolFailure, CommandDefinition } from "./protocol/protocol-guards.ts";

export { COMMAND_REGISTRY } from "./protocol/command-registry.ts";

export {
	methodResultSchema,
	isMethodResult,
	isSendResult,
	isInterruptResult,
	isMemberStatusResult,
	isMemberRequestResult,
	isGuestJoinResult,
	isMemberIdleWaitSubscribeResult,
	isMemberIdleWaitNotification,
	isSubscribeResult,
	isGetMessageResult,
	isExtractedMessage,
	isClearResult,
	buildResultResponse,
	buildErrorResponse,
	buildTurnEndNotification,
	buildMemberUpdateNotification,
	serializeRequest,
	serializeProtocolMessage,
	commandToRequest,
	requestToCommand,
	parseRequest,
} from "./protocol/protocol-helpers.ts";
